# Summary

This notebook shows that I successfully downloaded datasets from ImmPort using Method 2 and Method 3 by following the tutorial.

Method 3 shoulde be preferred. Because it queries the data directly from ImmPort API to identify the files to download, and the downloaded files contain all the necessary columns for analysis. This simplifies the data wrangling process.
I still need to understand Method 3 better to see how to download datasets of our interest from specific studies.

Tutorial: https://docs.immport.org/python/MultipleDownloadMethods.html

There are 3 methods to download data from ImmPort:
1. Download using the ImmPort Data Browser
2. Download using the ImmPort File Download API
3. Download using the ImmPort Query API

We need to download "immport_download.py". See https://docs.immport.org/filedownload/tool/

> The section below sets up the Python environment that is used by all the methods. This tutorial assumes you have downloaded the File Download Tool distribution available from ImmPort, that contains the bash shell script, the immport_download.py file and the Aspera executables. The immport_download.py file contains convience functions access the API, please review if you want more details. The tutorial assumes you have unzipped the distribution in a directory at the same level of notebook directory.

In [1]:
import sys
import os
import pandas as pd

# Set the Python path to the location of the directory containing "immport_download.py"
immport_download_code = "../../immport-data-download-tool/bin/" # Adjust this path as needed
sys.path.insert(0,immport_download_code)
os.chdir(immport_download_code)

import immport_download

In [ ]:
# Configure parameters
user_name = input("ImmPort Username: ")
password = input("ImmPort Password: ")
download_directory = "../../output" # Note: Avoid using parent paths with spaces to prevent potential issues
data_directory = "../../data"



# We only need it for Method 1
sdy212_directory= "../data/SDY212-DR58_Tab/Tab" # Path to SDY212 data directory 
# It is DR58 for the latest data release, We can find it from https://www.immport.org/browser/?path=SDY212&page=1

In [ ]:
# Method 1
# To view the contents of the ../data/SDY212-DR23_Tab/Tab directory, uncomment the command below
# %ls $sdy212_directory

ls: ../data/SDY212-DR23_Tab/Tab: No such file or directory

## Method 2: Download using the ImmPort File Download API

In [5]:
# Method 2

# ~~2025: DR59 (https://docs.immport.org/home/datareleaseschedule/?utm_source=chatgpt.com)~~
# https://www.immport.org/browser/?path=SDY212&page=1 -> DR58
# https://www.immport.org/browser/?path=ALLSTUDIES&page=1 -> DR59


immport_download.download_file(user_name,password,
                                    "/ALLSTUDIES/ALLSTUDIES-DR59_Metadata/subject.txt",download_directory)
immport_download.download_file(user_name,password,
                                    "/ALLSTUDIES/ALLSTUDIES-DR59_Metadata/arm_2_subject.txt",download_directory)
immport_download.download_file(user_name,password,
                                    "/ALLSTUDIES/ALLSTUDIES-DR59_Metadata/arm_or_cohort.txt",download_directory)
immport_download.download_file(user_name,password,
                                    "/ALLSTUDIES/ALLSTUDIES-DR59_Metadata/hai_result.txt",download_directory)

# immport_download.download_file(user_name,password,
#                                     "/ALLSTUDIES/ALLSTUDIES-DR23.zip",download_directory)

Session Stop  (Error: Server aborted session: No such file or directory)

Session Stop  (Error: Server aborted session: No such file or directory)

Session Stop  (Error: Server aborted session: No such file or directory)

Session Stop  (Error: Server aborted session: No such file or directory)

In [6]:
immport_download.download_file(user_name,password,
                                    'SDY212/SDY212-DR58_manifest.txt',download_directory)

Completed: 495K bytes transferred in 0 seconds
 (4931K bits/sec), in 1 file.

In [ ]:
immport_download.download_file(user_name,password,
                                    'SDY212/SDY212-DR58_Tab.zip',download_directory)

In [ ]:
immport_download.download_file(user_name,password,
                                    'SDY212/SDY212-DR58/subject.txt',download_directory)

Session Stop  (Error: Server aborted session: No such file or directory)

In [ ]:
print(download_directory)

/Users/wudaudau/Py projects/GitHub/ds-notebooks-and-tools/output

In [ ]:
print("download_directory =", download_directory)
print("abs =", os.path.abspath(download_directory))

download_directory = /Users/wudaudau/Py projects/GitHub/ds-notebooks-and-tools/output
abs = /Users/wudaudau/Py projects/GitHub/ds-notebooks-and-tools/output

In [12]:
%ls ../../output/SDY212-DR58_Tab/Tab

arm_2_subject.txt                 lk_lab_test_panel_name.txt
arm_or_cohort.txt                 lk_locus_name.txt
biosample.txt                     lk_mass_spectrometry_type.txt
biosample_2_treatment.txt         lk_organization.txt
contract_grant.txt                lk_personnel_role.txt
contract_grant_2_personnel.txt    lk_plate_type.txt
contract_grant_2_study.txt        lk_protein_name.txt
control_sample.txt                lk_protocol_type.txt
experiment.txt                    lk_public_repository.txt
experiment_2_protocol.txt         lk_race.txt
expsample.txt                     lk_reagent_type.txt
expsample_2_biosample.txt         lk_research_focus.txt
expsample_2_file_info.txt         lk_sample_type.txt
expsample_2_reagent.txt           lk_source_type.txt
expsample_2_treatment.txt         lk_species.txt
expsample_mbaa_detail.txt         lk_study_file_type.txt
expsample_public_repository.txt   lk_study_panel.txt
fcs_header.txt                    lk_subject_location.txt
fcs_header_marker.txt             lk_t0_event.txt
file_details.txt                  lk_time_unit.txt
file_info.txt                     lk_transcript_type.txt
hai_result.txt                    lk_unit_of_measure.txt
immune_exposure.txt               lk_user_role_type.txt
inclusion_exclusion.txt           lk_virus_strain.txt
lab_test.txt                      lk_visibility_category.txt
lab_test_panel.txt                mbaa_result.txt
lab_test_panel_2_protocol.txt     personnel.txt
lk_adverse_event_severity.txt     planned_visit.txt
lk_age_event.txt                  program.txt
lk_analyte.txt                    program_2_personnel.txt
lk_ancestral_population.txt       protocol.txt
lk_arm_type.txt                   protocols/
lk_cell_population.txt            reagent.txt
lk_cell_population_marker.txt     standard_curve.txt
lk_compound_role.txt              study.txt
lk_criterion_category.txt         study_2_condition_or_disease.txt
lk_data_completeness.txt          study_2_panel.txt
lk_disease.txt                    study_2_protocol.txt
lk_disease_stage.txt              study_categorization.txt
lk_ethnicity.txt                  study_data_release.txt
lk_exp_measurement_tech.txt       study_file.txt
lk_exposure_material.txt          study_link.txt
lk_exposure_process.txt           study_personnel.txt
lk_expsample_result_schema.txt    study_pubmed.txt
lk_file_detail.txt                subject.txt
lk_gender.txt                     treatment.txt
lk_hmdb.txt                       workspace.txt
lk_lab_test_name.txt

In [14]:
# Read in the 4 files and load into Panda's Data Frames, filter to SDY212

supplied_directory = "/SDY212-DR58_Tab/Tab"

subject_file = download_directory + supplied_directory + "/subject.txt"
arm_2_subject_file = download_directory + supplied_directory + "/arm_2_subject.txt"
arm_or_cohort_file = download_directory + supplied_directory + "/arm_or_cohort.txt"
hai_result_file = download_directory + supplied_directory + "/hai_result.txt"
subjects = pd.read_table(subject_file, sep="\t")
arm_2_subject = pd.read_table(arm_2_subject_file, sep="\t")
arm_or_cohort = pd.read_table(arm_or_cohort_file, sep="\t")
hai_results = pd.read_table(hai_result_file,sep="\t")

In [15]:
subjects = subjects[['SUBJECT_ACCESSION','GENDER','RACE']]
arm_2_subject = arm_2_subject[['SUBJECT_ACCESSION','ARM_ACCESSION','MIN_SUBJECT_AGE']]
# Filter only records for SDY212 using ARM_ACCESSION
arm_2_subject = arm_2_subject[arm_2_subject['ARM_ACCESSION'].isin(['ARM894','ARM895'])]
arm_2_subject.loc[arm_2_subject['ARM_ACCESSION'] == 'ARM894','ARM_NAME'] = "Young"
arm_2_subject.loc[arm_2_subject['ARM_ACCESSION'] == 'ARM895','ARM_NAME'] = "Old"
arm_2_subject_merged = pd.merge(subjects,arm_2_subject, left_on='SUBJECT_ACCESSION', right_on='SUBJECT_ACCESSION')
arm_2_subject_merged.head()

  SUBJECT_ACCESSION  GENDER   RACE ARM_ACCESSION  MIN_SUBJECT_AGE ARM_NAME
0         SUB134236  Female  White        ARM894            24.07    Young
1         SUB134237    Male  Asian        ARM894            24.97    Young
2         SUB134238  Female  White        ARM895            84.06      Old
3         SUB134239  Female  White        ARM895            61.84      Old
4         SUB134240  Female  White        ARM895            62.86      Old

In [16]:
# Simple Descriptive Statistics

arm_2_subject_merged.groupby('ARM_NAME').count()['SUBJECT_ACCESSION']

ARM_NAME
Old      61
Young    30
Name: SUBJECT_ACCESSION, dtype: int64

In [17]:
arm_2_subject_merged.groupby('GENDER').count()['SUBJECT_ACCESSION']

GENDER
Female    54
Male      37
Name: SUBJECT_ACCESSION, dtype: int64

In [ ]:
# https://docs.immport.org/apidocumentation/shareddataapi/study/
# https://immport.org/data/query/swagger-ui/index.html

In [ ]:
# https://docs.immport.org/filedownload/pythonexamples/

## Method 3

Download using the ImmPort Query API
This method will use the Query API to download a JSON file of HAI results for SDY212. Because the JSON file contains all the columns we need for analysis, this will simplify the creation of the data frame for analysis. The final counts for the descriptive statistics, may be slightly off, but this is expected because not all the subjects in the 2 ARM's have HAI results.

In [18]:
# Request a token, then make API call, then load into Pandas's DataFrame
token = immport_download.request_immport_token(user_name, password)
r = immport_download.api("https://api.immport.org/data/query/result/hai?studyAccession=SDY212",token)
hai_results = pd.read_json(r)

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_56341/3874998549.py:4: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  hai_results = pd.read_json(r)

In [26]:
hai_results.shape

(534, 41)

In [27]:
hai_results.head()

,resultId,ageEvent,ageEventSpecify,ageUnit,ancestralPopulation,armAccession,armName,biosampleAccession,biosampleType,biosampleSubtype,...,studyTimeT0EventSpecify,subjectAccession,subjectPhenotype,unitPreferred,unitReported,valuePreferred,valueReported,virusStrainPreferred,virusStrainReported,treatmentAccession
0,6525,Age at Study Day 0,NaN,Years,NaN,ARM895,Cohort_2,BS694652,Whole blood,NaN,...,NaN,SUB134240,Non-twin,Antibody titer,Antibody titer,20,20,B/Florida/4/2006,B,TRT266
1,6526,Age at Study Day 0,NaN,Years,NaN,ARM894,Cohort_1,BS694662,Whole blood,NaN,...,NaN,SUB134251,Non-twin,Antibody titer,Antibody titer,40,40,A/Brisbane/10/2007,H3N2,TRT266
2,6527,Age at Study Day 0,NaN,Years,NaN,ARM895,Cohort_2,BS694669,Whole blood,NaN,...,NaN,SUB134258,Non-twin,Antibody titer,Antibody titer,10,10,A/Brisbane/59/2007,H1N1,TRT266
3,6528,Age at Study Day 0,NaN,Years,NaN,ARM895,Cohort_2,BS694675,Whole blood,NaN,...,NaN,SUB134264,Non-twin,Antibody titer,Antibody titer,40,40,B/Florida/4/2006,B,TRT266
4,6529,Age at Study Day 0,NaN,Years,NaN,ARM895,Cohort_2,BS694681,Whole blood,NaN,...,NaN,SUB134271,Non-twin,Antibody titer,Antibody titer,640,640,A/Brisbane/10/2007,H3N2,TRT266

In [19]:
hai_results.columns

Index(['resultId', 'ageEvent', 'ageEventSpecify', 'ageUnit',
       'ancestralPopulation', 'armAccession', 'armName', 'biosampleAccession',
       'biosampleType', 'biosampleSubtype', 'clinical', 'comments',
       'ethnicity', 'experimentAccession', 'expsampleAccession', 'gender',
       'maxSubjectAge', 'measurementTechnique', 'minSubjectAge',
       'plannedVisitAccession', 'race', 'raceSpecify', 'repositoryAccession',
       'repositoryName', 'species', 'strain', 'studyAccession', 'studyTitle',
       'studyTimeCollected', 'studyTimeCollectedUnit', 'studyTimeT0Event',
       'studyTimeT0EventSpecify', 'subjectAccession', 'subjectPhenotype',
       'unitPreferred', 'unitReported', 'valuePreferred', 'valueReported',
       'virusStrainPreferred', 'virusStrainReported', 'treatmentAccession'],
      dtype='object')

In [20]:
# Remove column and rename to match names in the first 2 methods

arm_2_subject_merged = hai_results[['subjectAccession','armAccession','minSubjectAge','gender','race']]
arm_2_subject_merged=arm_2_subject_merged.rename(columns={'subjectAccession':'SUBJECT_ACCESSION'})
arm_2_subject_merged=arm_2_subject_merged.rename(columns={'armAccession':'ARM_ACCESSION'})
arm_2_subject_merged=arm_2_subject_merged.rename(columns={'minSubjectAge':'MIN_SUBJECT_AGE'})
arm_2_subject_merged=arm_2_subject_merged.rename(columns={'gender':'GENDER'})
arm_2_subject_merged=arm_2_subject_merged.rename(columns={'RACE':'RACE'})
arm_2_subject_merged.loc[arm_2_subject_merged['ARM_ACCESSION'] == 'ARM894','ARM_NAME'] = "Young"
arm_2_subject_merged.loc[arm_2_subject_merged['ARM_ACCESSION'] == 'ARM895','ARM_NAME'] = "Old"
arm_2_subject_merged.head()

  SUBJECT_ACCESSION ARM_ACCESSION  MIN_SUBJECT_AGE  GENDER   race ARM_NAME
0         SUB134240        ARM895            62.86  Female  White      Old
1         SUB134251        ARM894            29.23  Female  White    Young
2         SUB134258        ARM895            85.41  Female  White      Old
3         SUB134264        ARM895            68.08  Female  White      Old
4         SUB134271        ARM895            86.61  Female  White      Old

In [22]:
# Simple Descriptive Statistics

arm_2_subject_merged[['ARM_NAME','SUBJECT_ACCESSION']].drop_duplicates().groupby('ARM_NAME').count()

          SUBJECT_ACCESSION
ARM_NAME
Old                      60
Young                    29

In [23]:
arm_2_subject_merged[['GENDER','SUBJECT_ACCESSION']].drop_duplicates().groupby('GENDER').count()

        SUBJECT_ACCESSION
GENDER
Female                 54
Male                   35

In [ ]:
# Download Files Using Data Query and File Download API

token = immport_download.request_immport_token(user_name, password)
r = immport_download.api("https://api.immport.org/data/query/result/filePath?studyAccession=SDY212&armName=Cohort_1&measurementTechnique=Flow%20cytometry",token)
df = pd.read_json(r)
df = df[df['fileDetail'] == "Flow cytometry result"]
df_fcs = df[['subjectAccession','armAccession','armName','gender','race','minSubjectAge','studyTimeCollected', \
               'fileDetail','filePath']]
df_fcs.head()

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_56341/885769030.py:5: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(r)

,subjectAccession,armAccession,armName,gender,race,minSubjectAge,studyTimeCollected,fileDetail,filePath
22,SUB134242,ARM894,Cohort_1,Male,White,26.86,0,Flow cytometry result,/SDY212/ResultFiles/Flow_cytometry_result/PHOS...
23,SUB134249,ARM894,Cohort_1,Female,Other,26.01,0,Flow cytometry result,/SDY212/ResultFiles/Flow_cytometry_result/PHOS...
46,SUB134253,ARM894,Cohort_1,Female,Asian,22.67,0,Flow cytometry result,/SDY212/ResultFiles/Flow_cytometry_result/PHOS...
47,SUB134275,ARM894,Cohort_1,Male,White,21.95,0,Flow cytometry result,/SDY212/ResultFiles/Flow_cytometry_result/PHOS...
59,SUB134268,ARM894,Cohort_1,Female,White,29.71,0,Flow cytometry result,/SDY212/ResultFiles/Flow_cytometry_result/PHOS...

In [25]:
unique_file_paths = df_fcs.filePath.unique()
unique_fcs_paths = [path for path in unique_file_paths if path.endswith(".fcs")]
for i in range(0,5):
    print("Downloading: ",unique_fcs_paths[i])
    immport_download.download_file(user_name,password,
                                    unique_fcs_paths[i],download_directory)

Downloading:  /SDY212/ResultFiles/Flow_cytometry_result/PHOSPHOFLOW SPECIMEN_FLU 010V1.390100.fcs
Completed: 52612K bytes transferred in 6 seconds
 (66525K bits/sec), in 1 file.
Downloading:  /SDY212/ResultFiles/Flow_cytometry_result/PHOSPHOFLOW SPECIMEN_FLU 018V1.390104.fcs
Completed: 35149K bytes transferred in 4 seconds
 (64042K bits/sec), in 1 file.
Downloading:  /SDY212/ResultFiles/Flow_cytometry_result/PHOSPHOFLOW SPECIMEN_022V1.390144.fcs
Completed: 72898K bytes transferred in 7 seconds
 (75378K bits/sec), in 1 file.
Downloading:  /SDY212/ResultFiles/Flow_cytometry_result/PHOSPHOFLOW SPECIMEN_047V1.390160.fcs
Completed: 95630K bytes transferred in 12 seconds
 (61232K bits/sec), in 1 file.
Downloading:  /SDY212/ResultFiles/Flow_cytometry_result/PHOSPHOFLOW SPECIMEN_039V1.391052.fcs
Completed: 64683K bytes transferred in 7 seconds
 (70265K bits/sec), in 1 file.